# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20171219_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
