# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='seen',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
