# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20171221_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='explanation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
