# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20171221_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary',
            field=models.CharField(choices=[(1, 'Omnivore'), (2, 'Carnivore'), (3, 'Herbivore')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetables',
            field=models.TextField(blank=True, null=True),
        ),
    ]
